### ISSUE TITLE
Error in finding difference set when line coincides

### ISSUE THREAD

**Issue by renhuailiang** [w8r/GreinerHormann#17]
var selfpointvec = [{"x":0,"y":0},{"x":10,"y":10},{"x":15,"y":5},{"x":20,"y":10},{"x":25,"y":0}];
    var otherpointvec = [{"x":6,"y":6},{"x":8,"y":8},{"x":25,"y":8},{"x":25,"y":6}];
let m = clip(selfpointvec,otherpointvec, false, true);
    for(var i = 0;i<m.length;i++) {
        console.log(JSON.stringify(m[i]));
    }
/****************/
[{"x":12,"y":8},{"x":10,"y":10},{"x":0,"y":0},{"x":25,"y":0},{"x":22,"y":6},{"x":25,"y":6},{"x":25,"y":8},{"x":21,"y":8},{"x":20,"y":10},{"x":18,"y":8},{"x":12,"y":8}]
[{"x":14,"y":6},{"x":15,"y":5},{"x":16,"y":6},{"x":14,"y":6}]

**Comment by w8r** [comment]
Greiner Hormann algorithm is by design not really good for degenerate polygons (self-intersections, coinciding points). I would suggest moving the coinciding point by a small &epsilon;

Also, here's my other library, that is capable of doing it, check out with your input 
https://codepen.io/w8r/pen/rrBkER

https://github.com/w8r/martinez

**Comment by renhuailiang** [comment]
Thank you for your prompt reply
